name: Build and Test

on: 
  push: 
    branches: 
    - master 
  pull_request: 
    branches: 
    - master 

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux:
    # The jobs should run pretty quick; anything over 30m essentially means
    # someting is stuck somewhere
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_YML_JOBNAME: ${{ matrix.os }}-${{ matrix.compiler }}
      GH_YML_BUILDTYPE: ${{ matrix.buildtype }}
      GH_YML_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

    strategy:
      fail-fast: false
      matrix:
        buildtype: [ release, debug ]
        os: [ centos8, ubuntu2204, ubuntu2404 ]
        compiler: [ clang, gcc, nvhpc ]
        exclude:
          - { os: centos8, compiler: nvhpc }
          - { os: ubuntu2204, compiler: nvhpc }
        include:
        - os: centos8
          container: centos:8
        - os: ubuntu2404
          container: ubuntu:24.04
        - os: ubuntu2204
          container: ubuntu:22.04
        - os: centos7
          compiler: nvhpc
          container: nvcr.io/nvidia/nvhpc:21.2-devel-cuda11.2-centos7
        - os: ubuntu2404
          compiler: nvhpc
          container: nvidia/cuda:12.9.1-devel-ubuntu24.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: source
    - name: Setup
      run: source/scripts/ci/setup/linux.sh
    - name: Update
      run: source/scripts/ci/gh-actions/run.sh update
    - name: Configure
      run: source/scripts/ci/gh-actions/run.sh configure
    - name: Build
      run: source/scripts/ci/gh-actions/run.sh build
    - name: Test
      run: source/scripts/ci/gh-actions/run.sh test

  mac_and_windows:
    # The jobs should run pretty quick; anything over 30m essentially means
    # someting is stuck somewhere
    timeout-minutes: 30
    runs-on: ${{ matrix.vm }}
    env:
      GH_YML_JOBNAME: ${{ matrix.jobname }}
      GH_YML_BUILDTYPE: ${{ matrix.buildtype }}
      GH_YML_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

    strategy:
      fail-fast: false
      matrix:
        buildtype: [ release, debug ]
        jobname: [
          windows-vs2019-msvc,
          windows-vs2019-clang,
          macos-clang ]
        include:
        - jobname: windows-vs2019-msvc
          vm: windows-latest
        - jobname: windows-vs2019-clang
          vm: windows-latest
        - jobname: macos-clang
          vm: macos-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: source
    - name: Setup
      if: ${{ runner.os == 'Windows' }}
      run: source/scripts/ci/setup/windows.sh
    - name: Setup
      if: ${{ runner.os == 'macOS' }}
      run: source/scripts/ci/setup/macos.sh
    - name: Update
      run: source/scripts/ci/gh-actions/run.sh update
    - name: Configure
      run: source/scripts/ci/gh-actions/run.sh configure
    - name: Build
      run: source/scripts/ci/gh-actions/run.sh build
    - name: Test
      run: source/scripts/ci/gh-actions/run.sh test
